### ISSUE TITLE
Turn on pin from switch_id

### ISSUE THREAD

**Issue by eadlam** [kadlam/smhome#1]
In the switches view file https://github.com/kadlam/smhome/blob/master/switches/views.py

On line 53, you should be querying the sprinkler object via the switch_id like this:

```
sprinkler = Switch.objects.get(id=switch_id)
```

Then on line 54 you can do

```
bot.turnOn(sprinkler.pinId)
```

**Comment by kadlam** [comment]
See updated views.py & models.py
Things work as they should except query for sprinkler 3 fails because evidently - early on - the id-3 in sqlite was deleted so the dbase looks like this:
    >>> Switch.objects.values_list('id').order_by('id')
    [(1,), (2,), (4,), (5,), (6,), (7,)]

Will try to fix using sqlite otherwise create new db

**Comment by kadlam** [comment]
Does not appear an id number can be changed in sqlite.
Ran a new migration; created new db.sqlite3 file in /sprinklerservice; re-entered sprinkler name, location, pinId data in localserver:8000/admin. Now id numbers 1 through 6 properly correspond to sprinklers 1-6 and associated RPi output pins. Now
    >>> Switch.objects.values_list('id').order_by('id')
    [(1,), (2,), (3,), (4,), (5,), (6,)]
